# $FreeBSD$

PORTNAME=	runc
PORTVERSION=	2019112601
DISTVERSIONPREFIX=	v
CATEGORIES=	sysutils

MAINTAINER=	heliocentric@gmail.com
COMMENT=	blah blah blah

LICENSE=	MPL20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=           go:modules
USE_GITHUB=	yes
GH_ACCOUNT=	niftyengineering
GH_TAGNAME=     b5218c702a1782f68d5ba50033e2f0788ccb735a

.include <bsd.port.mk>

